
get http://localhost:3003/tasks
content-Type: application/json


###


post http://localhost:3003/tasks
content-Type: application/json

{
    "taskText": "do party"
}


###

delete http://localhost:3003/tasks/2
content-Type: application/json

###

post http://localhost:3003/auth
content-Type: application/json

{
    "username": "nadia",
    "password": "password"
}

###

post http://localhost:3003/auth/login
content-Type: application/json

{
    "username": "nadia",
    "password": "password"
}

###
put http://localhost:3003/tasks/checkbox/2
content-Type: application/json

{
    "checkbox": true   
}
